// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgxrDey3RSwXCumc87wydfA6Nx81mGb0k',
    appId: '1:651003632744:android:dea31a8edbe34c62bb2fdd',
    messagingSenderId: '651003632744',
    projectId: 'image-uploader-ad1f7',
    databaseURL: 'https://image-uploader-ad1f7-default-rtdb.firebaseio.com',
    storageBucket: 'image-uploader-ad1f7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVOnX50lwbXGLt7Lb-ikLsogKiE_VjO2Y',
    appId: '1:651003632744:ios:1db6ffc8fb8a3a61bb2fdd',
    messagingSenderId: '651003632744',
    projectId: 'image-uploader-ad1f7',
    databaseURL: 'https://image-uploader-ad1f7-default-rtdb.firebaseio.com',
    storageBucket: 'image-uploader-ad1f7.appspot.com',
    iosBundleId: 'com.example.imageUpload',
  );

}